repos:
  - repo: https://github.com/jguttman94/pre-commit-gradle
    rev: v0.2.1
    hooks:
      - id: gradle-check
  - repo: https://github.com/ThomasKoppensteiner/google-style-precommit-hook/
    rev: v1.0.0
    hooks:
      - id: google-style-java
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
